name: Build README

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Check out repo
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.12.0

      - name: Npm install
        run: npm install
      
      - name: Run script and Update REAMDE.md
        run: node script/index.js > README.md

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "249900679@qq.com"
          git config --global user.name "CodeBear"
          git pull origin master
          git add -A
          git commit -m "Build README" || exit 0
          git push origin master
